Andrii sas
kolyasalubov/Lv-627.PythonProject pull request #38
Opened 2021-09-02 20:10 UTC by Andriisas

2021-09-02 21:25 UTC, Oleg-Smal-git approved these changes
LGTM.

2021-09-03 07:48 UTC, CheshirLvova requested changes

2021-09-03 07:48 UTC, CheshirLvova commented on Tasks/task_325.py
>  task_325 = Task(
change this part like this:

task_325 = Task(
    name="task_325",
    description=
    """
    Please, add your description
    """,
    body=_task,
    test="Tasks/test_task_325.py"
)

2021-09-03 07:48 UTC, CheshirLvova commented on Tasks/test_task_328.py
> +        ]
add newline

2021-09-03 07:48 UTC, CheshirLvova commented on Tasks/test_task_328.py
> +    assert task_328._task() == [
there must be ...task_328.run_body()...

2021-09-04 16:51 UTC, CheshirLvova approved these changes
nice)

2021-09-06 10:31 UTC, v-lavrushko requested changes

2021-09-06 10:31 UTC, v-lavrushko commented on Tasks/task_086v.py
> +def _task(value : int) -> int:
please add docstring

2021-09-06 10:31 UTC, v-lavrushko commented on Tasks/test_task_113a.py
> -
every class - 2 blank lines (PEP8)

2021-09-06 10:31 UTC, v-lavrushko commented on Tasks/task_325.py
> +def prime_number(num : int) -> bool:
there is a better algorithm. Can help with it

2021-09-10 11:09 UTC, OlehHnyp approved these changes

2021-09-10 11:11 UTC, v-lavrushko approved these changes

2021-09-10 11:49 UTC, merged