Additional tests to tasks 086a, 086b, and 330 have been added.
kolyasalubov/Lv-627.PythonProject pull request #40
Opened 2021-09-03 11:15 UTC by MykhailoGrynenko

2021-09-03 12:23 UTC, CheshirLvova requested changes

2021-09-03 12:23 UTC, CheshirLvova commented on Tasks/test_task_086a.py
> +    def test_task_559(self) -> None:
change name of the function according to your tests

2021-09-03 12:23 UTC, CheshirLvova commented on Tasks/test_task_086b.py
> +    def test_task_559(self) -> None:
change name of the function according to your tests

2021-09-03 12:23 UTC, CheshirLvova commented on Tasks/test_task_330b.py
> +    def test_task_559(self) -> None:
change name of the function according to your tests

2021-09-03 12:23 UTC, CheshirLvova commented on Tasks/test_task_086b.py
> +        with pytest.raises(TaskError):
0 won't call TaskError

2021-09-03 12:23 UTC, CheshirLvova commented on Tasks/test_task_086a.py
> +        with pytest.raises(TaskError):
0 won't call task error

2021-09-03 12:23 UTC, CheshirLvova commented on Tasks/test_task_086a.py
> +        with pytest.raises(TaskError):
here is also an exception would be call, so there would be assertEqual
(and after that you won't need module

2021-09-03 12:23 UTC, CheshirLvova commented on Tasks/test_task_086b.py
> +        with pytest.raises(TaskError):
exception

2021-09-03 12:23 UTC, CheshirLvova commented on Tasks/test_task_330b.py
> +        with pytest.raises(TaskError):
exception

2021-09-03 12:23 UTC, CheshirLvova commented on Tasks/test_task_330b.py
> +        with pytest.raises(TaskError):
exception

2021-09-03 13:39 UTC, MykhailoGrynenko commented on Tasks/test_task_086a.py
> +    def test_task_559(self) -> None:
Thank you. You are quite perceptive.

2021-09-03 13:39 UTC, MykhailoGrynenko commented on Tasks/test_task_086b.py
> +    def test_task_559(self) -> None:
Thank you.

2021-09-03 13:41 UTC, MykhailoGrynenko commented on Tasks/test_task_086b.py
> +        with pytest.raises(TaskError):
I'm sorry, I'm afraid, I don't understand you.
I added another test:
        with pytest.raises(TaskError):
            task_330.run_body(0)
Thank you for your feedback!

2021-09-10 11:53 UTC, v-lavrushko commented on Tasks/test_task_086a.py
> +        with pytest.raises(TaskError):
is this a comment to test, or task itself?)

2021-09-10 12:10 UTC, CheshirLvova requested changes
change  titles of some funcs

2021-09-10 12:10 UTC, CheshirLvova commented on Tasks/test_task_086a.py
> +    def test_task_330(self) -> None:
not 330, but 086a

2021-09-10 12:10 UTC, CheshirLvova commented on Tasks/test_task_086a.py
> +        with pytest.raises(TaskError):
hehe, to test)

2021-09-10 12:10 UTC, CheshirLvova commented on Tasks/test_task_086b.py
> +    def test_task_330(self) -> None:
not 330, but 086b

2021-09-12 14:38 UTC, MykhailoGrynenko commented on Tasks/test_task_086a.py
> +    def test_task_330(self) -> None:
Thanks.

2021-09-12 14:38 UTC, MykhailoGrynenko commented on Tasks/test_task_086b.py
> +    def test_task_330(self) -> None:
Thanks.

2021-09-13 16:24 UTC, OlehHnyp approved these changes

2021-09-13 16:36 UTC, CheshirLvova approved these changes
everything ok

2021-09-13 16:36 UTC, ProkhvatylovArtem approved these changes

2021-09-13 16:37 UTC, ruslanliska approved these changes

2021-09-14 08:40 UTC, merged